# Specify base image
FROM node:12.20.2-alpine
WORKDIR "/app"

# Install dependencies
COPY ./package.json ./
RUN npm install -g @angular/cli
RUN npm install
COPY . .

# Default command
CMD ng serve --host 0.0.0.0