language: node_js
node_js:
  - '10'

before_cache:
  # awss3-deploy
  - pip install --user awscli

before_script: cd client

before_deploy:
  - export BUCKET=5mingames LOCAL_DIR=dist
  - ng build

cache:
  directories:
     - ./node_modules

deploy:
  - provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID 
  secret_access_key: $AWS_SECRET_ACCESS_KEY 
  bucket: "fivemingames"
  skip_cleanup: true