language: node_js
node_js:
  - "12"

before_script:
  - cd client
  - npm install
  - npm install -g @angular/cli

env:
  - socket_host = $SOCKET_HOST
  - socket_port = $SOCKET_PORT

script:
  - ng build --prod

cache:
  npm: false
  #directories:
  #  - ./node_modules

# deploy:
#   provider: s3
#   access_key_id: $AWS_ACCESS_KEY_ID
#   secret_access_key: $AWS_SECRET_ACCESS_KEY
#   local_dir: dist/fourinrow
#   bucket: "fivemingames"
#   skip_cleanup: true

branches:
  only:
    - master
