version: "3"
services:
  dao:
    build:
      dockerfile: Dockerfile.dev
      context: ./redis
    expose:
      - 6379
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "4200:80"
      - "5000:80"
    depends_on:
      - api
      - client
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - DAO_HOST=dao
      - DAO_PORT=6379
      - SERVER_PORT=5000
      - SERVER_ALLOW_ORIGIN=http://localhost:4200
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
